name: Validate exercises JSON

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/src/main/res/raw/exercises.json'
      - 'app/src/main/assets/**'
  pull_request:
    paths:
      - 'app/src/main/res/raw/exercises.json'
      - 'app/src/main/assets/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python validate_exercises_json.py

      - name: Upload ordered JSON
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: ordered_exercises.json
          archive: false